# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: ctrl industries
email: chris@ctrl.industries
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chris Castle
  pic: crc
  position: Product Manager, Software Engineer, Hardware Engineer
  social:
    - title: email
      url: mailto:chris@ctrl.industries
    - title: user
      url: https://crc.io/resume/
    - title: github
      url: https://github.com/crcastle
    - title: twitter
      url: https://twitter.com/crc

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 109b 19th Ave
  - line: Seattle, WA 98122

modals:
  - id: 1
    title: LPG Consumption in United States
    description:
    img: LPG By State.png
    source_description: U.S. Energy Information Administration Data
    source_url: https://docs.google.com/spreadsheets/d/119rs7p-vMex2iENfmvTRFssNuVe2B4LQlfCl8bHRd6s/edit?usp=sharing
  - id: 2
    title: "\"Smart\" Consumer Devices"
    description:
    img: smart-devices.png
  - id: 3
    title: Increasing Value Over Time
    description:
    img: saas-value-prop.jpg

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor, bin, fonts, Gemfile, Gemfile.lock, LICENSE, Rakefile, README.md, TODO.md]
kramdown:
  parse_block_html: true
